### ISSUE TITLE
Cannot find data cache

### ISSUE THREAD

**Issue by kenorb** [sebastianschroeter/issuu-downloader#1]
I've compiled app on OSX as:

```
$ brew install maven
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home mvn install
$ cd target
$ java -jar issuuDownloader.jar "http://issuu.com/x/docs/x/1"
```

But when running, I've got error:

```
Cannot find data cache
```

Does it mean the code no longer works?

**Comment by sebastianschroeter** [comment]
The issuu site you want to download does not exist. Try this as url: "http://issuu.com/ukscouting/docs/outdoor_adventure_manual"

Just tested it and it works fine.

**Comment by kenorb** [comment]
Thanks, it works now, maybe I've missed something, thank you.
However I've managed to write my own script ([dl_issuu.sh](https://github.com/kenorb/kenorb/blob/master/scripts/shell/dl_issuu.sh)).
